code: 131067
gijiroku: data/gijiroku.csv
giin: data/giin.csv
iinkai: data/iinkai.csv
years: data/years.csv
jogai: data/exclusion.csv
font: static/ShipporiMinchoB1-ExtraBold.ttf
target:
  place: 台東区
  start: 1993年3月
  end: 2022年7月
  url: http://taito.gijiroku.com/voices/index.asp
developer:
  name: 岡村健一
  contact: https://twitter.com/Okamura_Kenichi
  img: static/developer.png